# Generated by Django 3.2.8 on 2021-10-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Normas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='expediente',
            field=models.FileField(blank=True, null=True, upload_to='DOC_EXPEDIENTES', verbose_name='Expediente Adjunto'),
        ),
    ]
