# Generated by Django 3.2.9 on 2021-11-07 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Normas', '0002_expediente_expediente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='entidad',
            field=models.CharField(blank=True, default='Entidad', max_length=200, null=True, verbose_name='Entidad:'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='expediente',
            field=models.FileField(help_text='Adjuntar Archivo', upload_to=''),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='fecha_documento',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha:'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='tipo_documento',
            field=models.CharField(blank=True, default='Tipo', max_length=50, null=True, verbose_name='Tipo Documento:'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='titulo',
            field=models.CharField(blank=True, default='Titulo', max_length=300, null=True, verbose_name='Titulo:'),
        ),
    ]
